services:
  pg:
    build:
      dockerfile: pg.dockerfile
      context: '.'
      labels:
        com.docker.compose.container-number: "1"
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin"]
      interval: 1s
      timeout: 5s
      retries: 10
  vault:
    image: hashicorp/vault:1.13.0
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
    ports:
      - "8200:8200"
